### ISSUE TITLE
SpringBoot 개발 환경 설정

### ISSUE THREAD

**Issue by byeong-chang** [byeong-chang/Stand_Up_Seoul#6]
JDK

Amazon Correto 11
Java
11
Spring Boot Dependency
Spring Boot DevTools
Lombok
Spring Web
Spring Security
Thymeleaf
MysQL Driver
Spring Data JPA

**Comment by sangwookWoo** [comment]
아주 좋군요~

**Comment by byeong-chang** [comment]
ㅆ
